server: 
  port: 8085
  servlet:
    context-path: /step-server
logging:
  level:
    org.springframework: INFO
####### resource server configuration properties
spring:
  profiles:
    active: test
  application:
    name: eureka-step-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        path: /h2-console
        enabled: true
        settings:
          web-allow-others: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:100@localhost:8090/eureka
  instance:
    preferIpAddress: false
  healthcheck:
    enabled: true