spring:
  application:
    name: spring-cloud-eureka-client-1
  security:
    sessions: STATELESS
    oauth2:
      client:
        registration:
          custom:
            client-id: ssoClient-1
            client-secret: ssoClientSecret-1
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/ui-one/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8083/auth/realms/sviridov/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/sviridov/protocol/openid-connect/token
            user-info-uri: http://localhost:8083/auth/realms/sviridov/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8082
  servlet: 
    context-path: /ui-one
    
logging: 
  level: 
    org.springframework: INFO

resourceserver:
  api:
    url: http://localhost:8089/instruction-server/api/foos/

