server: 
  port: 8081
  servlet:
    context-path: /instruction-server
logging:
  level:
    org.springframework: DEBUG
####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/sviridov
          jwk-set-uri: http://localhost:8083/auth/realms/sviridov/protocol/openid-connect/certs
  profiles:
    active: test
  application:
    name: eureka-instruction
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        path: /h2-console
        enabled: true
        settings:
          web-allow-others: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:100@localhost:8090/eureka
  instance:
    preferIpAddress: false
  healthcheck:
    enabled: true
  feign:
    step-service-name: eureka-step-service
    levels-service-name: eureka-levels-service
